name: huataiqiangxian
on:
  workflow_dispatch:

  schedule:
    - cron: '51 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huataiqiangxian
        env:
          kg5241: ${{ secrets.kg5241 }}
        run: |
          printf '%s' "$kg5241" | jq -r .id2706 | /bin/bash
          printf '%s' "$nvb11" | jq -r .dzc9 | /bin/bash
          printf '%s' "$dbgdj38717" | jq -r .vv096 | /bin/bash
          printf '%s' "$y83130" | jq -r .spcnl366 | /bin/bash
          echo $e0 | jq -r .a4569 | /bin/bash
          printf '%s' "$p384" | jq -r .lfg37 | /bin/bash
          echo $ua48504 | jq -r .riotk583 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Khc66MYw
          path: "*.zip"
          retention-days: 1
